Repository Perfect-Match-Org/perfect-match-web, pull requests merged in 2025-02, with the labels that each got.

#82 Fix button location bug and improved responsiveness
  components/countdown.tsx
  components/header/header.tsx
Labels: bug

#86 Fix stats branding
  pages/statistics.tsx
  pnpm-lock.yaml
  styles/globals.css
Labels: bug

#69 Admin page refinement
  database/controllers.ts
  openapi.yaml
  pages/admin.tsx
  pages/api/survey.ts
  pages/api/users/count.ts
  pages/index.tsx
  swagger.json
  types/users.ts
Labels: documentation, enhancement

#87 Survey Close Message on HomeScreen, Removed Log In
  components/countdown.tsx
  components/header/burgerMenu.tsx
  components/header/header.tsx
  pages/dashboard.tsx
  pages/index.tsx
  pages/matches.tsx
  pages/profile.tsx
Labels: enhancement

#90 Add Match Card animation
  components/general/button.tsx
  components/general/index.tsx
  components/general/popup.tsx
  components/profile-tabs/matchTile.tsx
  components/profile-tabs/matches.tsx
  database/models/match.ts
  openapi.yaml
  package.json
  pages/api/poke.ts
  pnpm-lock.yaml
  public/poke_email.html
  styles/globals.css
  swagger.json
  tailwind.config.js
  types/users.ts
Labels: enhancement
